services:
  - type: web
    name: strume-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: ACOUSTID_API_KEY
        value: your-api-key-here

  - type: web
    name: strume-frontend
    env: static
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    buildFilter:
      paths:
        - frontend/**/*
